### ISSUE TITLE
HTTPS question

### ISSUE THREAD

**Issue by nwestendorf** [dm-guy/utm-alternative#3]
This isn't an issue so much as a question.  Apologies if it's an inappropriate use of Issue reporting.

In the case of HTTPS sites (quite numerous .. including twitter and facebook), have you found any creative workaround to not having document.referrer available?

**Comment by dm-guy** [comment]
Unfortunately not. But if your site is on HTTPS, you won't have a problem (the document.referrer is dropped when linking from HTTPS to HTTP, but not HTTPS to HTTPS, at the time of writing).
