### ISSUE TITLE
no cookie is being created

### ISSUE THREAD

**Issue by bobbylechuga** [dm-guy/utm-alternative#6]
Very good library! I have a problem for a website where I use: no cookie is being created. I realized that the document.form_contacto ["entry.2142106093"] value = getCookie ("traffic_source."); It is always "undefined". Unlike other websites where I did work, it is a form of google. Is that the problem?

Thanks in advance.

:)

**Comment by dm-guy** [comment]
Do you still have this issue? The issue was open and then closed.

**Comment by bobbylechuga** [comment]
Yes, I closed because writing the problem, I found the solution. The site has two domains, and mistakenly configured the redirection does not the principal. Thanks for asking.
