### ISSUE TITLE
how to read utm_* url parameters

### ISSUE THREAD

**Issue by ebaschiera** [dm-guy/utm-alternative#9]
Hi,
thank you for you effort!
I have a question... Do you think it would be feasible to edit your script and adapt it to intercept classic utm_\* url parameters?
In Mailchimp, for example, there are some handy automations that prepare the urls for the newsletter, adding utm_\* parameters. I might intercept those parameters (instead of src parameter) and set the cookies accordingly. Then I can read those cookies in the usual methods I was using before universal tracker.
I'd like to hear from you.

Thanks a lot!

**Comment by dm-guy** [comment]
Hi, 
Using the utm_campaign and others is a possibility, however I am not sure I will have the time to do so in the coming period. I use mailchimp as well and I add the "src" manually. I'll post again when this requirement is added to the script.

**Comment by dm-guy** [comment]
Hi, pleased to share that the new release of the plugin supports the use case that you described. You are welcome to visit the plugin page for the new version.
